### ISSUE TITLE
Put database operations in separate package 

### ISSUE THREAD

**Issue by vbmade2000** [sbinet-alt63/strew#2]
IMHO it is good to put database logic in separate package. This way We can support more databases in future. Also it makes code more maintainable.

**Comment by sbinet** [comment]
SGTM.

I'd start with a very light interface:

```go
type DB interface {
   Subscribers(list string) ([]string, error)
   Subscribe(user, list string) error
   Usubscribe(user, list string) error
   Lists() ([]string, error)
   Users() ([]string, error)
}
```

What do you think?
Do you want to try a PR?

**Comment by vbmade2000** [comment]
Sure.

**Comment by vbmade2000** [comment]
Looks like Lists() doesn't fetch records from db. It reads data from config file. Correct me if I am wrong.

**Comment by sbinet** [comment]
yes, right now, `Lists()` doesn't fetch informations from the db.

I must say I am still on the fence on this one.
Probably, for consistency, I would be probably leaning on having everything stored in the db, the configuration file being just the initial "seed" for the db content.
