### ISSUE TITLE
strew: add gofmt check in travis

### ISSUE THREAD

**Issue by vbmade2000** [sbinet-alt63/strew#8]

**Comment by vbmade2000** [comment]
Actually it should be added to travis.yml so that it can be checked every time we [ush the code :)

**Comment by sbinet** [comment]
it's actually run as part of travis.
travis does:

- `go get -v ./...`
- `go test -v ./...`

see: https://travis-ci.org/sbinet-alt63/strew/jobs/352772315

**Comment by vbmade2000** [comment]
Cool. I didn't know that.
